apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saas-app.fullname" . }}-secrets
  namespace: {{ .Values.tenant.namespace }}
  labels:
    {{- include "saas-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ randAlphaNum 32 | quote }}
